name: Build and Deploy to AWS test 4

on:
  push:
    branches: [ s3-test ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - uses: actions/setup-node@v1
        name: Setup Node.js
        with:
          node-version: '13.x'
      - run: npm install
        name: Install npm
      - run: npm install --save-dev
        name: Install npm dependencies
      - run: gulp
        name: Build
      - uses: jakejarvis/s3-sync-action@master
        name: Deploy to AWS
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: 'build'